/**
 * The R sandbox (CODE-018): webR runs in an `<iframe sandbox="allow-scripts">`
 * of its own, with an opaque origin like the code sandbox (no access to the
 * application's storage or DOM). webR downloads its files itself, some of them
 * with synchronous requests, so this sandbox may reach the network — only the
 * webR CDN and its package repository, once the user agreed.
 *
 * webR needs 'unsafe-eval' (code generated by Emscripten), which the
 * application's own policy does not allow: so this sandbox is a page of its
 * own, `public/r-sandbox.html` (generated from this module, see
 * tests/code.r-sandbox.test.ts), loaded in the frame — not a `srcdoc`, which
 * would inherit the application's policy.
 */

export const WEBR_VERSION = '0.6.0';
export const WEBR_ORIGIN = 'https://webr.r-wasm.org';
export const WEBR_REPO = 'https://repo.r-wasm.org';
export const WEBR_BASE = `${WEBR_ORIGIN}/v${WEBR_VERSION}/`;

/** Runs R code sent by the application with webR, and sends back its output and plots. */
export const R_BOOTSTRAP = `
let webR;
const toPng = async (bitmap) => {
  const canvas = new OffscreenCanvas(bitmap.width, bitmap.height);
  const ctx = canvas.getContext('2d');
  ctx.fillStyle = '#fff';
  ctx.fillRect(0, 0, bitmap.width, bitmap.height);
  ctx.drawImage(bitmap, 0, 0);
  return (await canvas.convertToBlob({ type: 'image/png' })).arrayBuffer();
};
addEventListener('message', async (event) => {
  if (event.source !== parent) return;
  const m = event.data;
  if (!m || m.type !== 'run') return;
  const post = (data, transfer) => parent.postMessage({ id: m.id, ...data }, '*', transfer || []);
  try {
    if (!webR) {
      post({ type: 'status', status: 'loading' });
      // webR compares its URL with the page's origin, which is "null" in a sandbox: a valid stand-in is given.
      const source = (await (await fetch('${WEBR_BASE}webr.mjs')).text()).replace(/new URL\\((\\w+),location\\.origin\\)/g, 'new URL($1,"https://sandbox.invalid")');
      const mod = await import(URL.createObjectURL(new Blob([source], { type: 'text/javascript' })));
      const r = new mod.WebR({ baseUrl: '${WEBR_BASE}', repoUrl: '${WEBR_REPO}/bin/emscripten/contrib/', channelType: mod.ChannelType.PostMessage, interactive: false });
      await r.init();
      webR = r;
    }
    post({ type: 'status', status: 'running' });
    const shelter = await new webR.Shelter();
    try {
      const cap = await shelter.captureR(m.code, { withAutoprint: true, captureStreams: true, captureConditions: false, captureGraphics: { width: 576, height: 384 } });
      const text = cap.output.filter((o) => o.type === 'stdout' || o.type === 'stderr').map((o) => o.data + '\\n').join('');
      const images = [];
      for (const bitmap of cap.images || []) images.push(await toPng(bitmap));
      post({ type: 'result', text, images }, images);
    } finally {
      shelter.purge();
    }
  } catch (err) {
    post({ type: 'result', text: (err && err.message ? err.message : String(err)) + '\\n', error: true, images: [] });
  }
});
parent.postMessage({ type: 'ready' }, '*');
`;

export function rPolicy(bootstrapHash: string): string {
  return [
    "default-src 'none'",
    `script-src '${bootstrapHash}' ${WEBR_ORIGIN} blob: 'unsafe-eval' 'wasm-unsafe-eval'`,
    `worker-src blob: ${WEBR_ORIGIN}`,
    `connect-src ${WEBR_ORIGIN} ${WEBR_REPO} blob: data:`,
    'img-src blob: data:',
    "style-src 'unsafe-inline'",
  ].join('; ');
}

/** The page of the R sandbox, given the SHA-256 of its bootstrap (base64). */
export function rSandboxHtml(hashBase64: string): string {
  const hash = `sha256-${hashBase64}`;
  return (
    '<!doctype html>\n<!-- Generated from src/code/r-frame-html.ts: do not edit. -->\n<html><head><meta charset="utf-8">' +
    `<meta http-equiv="Content-Security-Policy" content="${rPolicy(hash)}">` +
    `</head><body><script type="module">${R_BOOTSTRAP}</script></body></html>\n`
  );
}
