# Potentiel électrique de deux charges opposées (unités arbitraires)
x, y = np.meshgrid(np.linspace(-2, 2, 300), np.linspace(-1.5, 1.5, 225))
V = 1 / np.hypot(x - 0.5, y) - 1 / np.hypot(x + 0.5, y)
V = np.clip(V, -5, 5)

plt.figure(figsize=(6, 4.2))
plt.contourf(x, y, V, levels=30, cmap="RdBu_r")
plt.colorbar(label="V")
plt.contour(x, y, V, levels=[-2, -1, -0.5, 0.5, 1, 2], colors="k", linewidths=0.6)
plt.plot([0.5, -0.5], [0, 0], "ko")
plt.gca().set_aspect("equal")
plt.xlabel("x")
plt.ylabel("y")
plt.tight_layout()
